language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-22

script: ./gradlew build connectedCheck

before_install:
 - chmod +x gradlew
 
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
