language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-22
    - sys-img-armeabi-v7a-android-22

script: ./gradlew build connectedCheck

before_install:
 - chmod +x gradlew
