language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - sys-img-armeabi-v7a-android-22
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-support-license-.+'

script: ./gradlew build connectedCheck

before_install:
 - chmod +x gradlew
